<?php
require_once 'Car.php';

class ElectriqueCar extends Car
{
    public int $batteryAutonomy;

    public function __construct(float $price, string $brand, int $batteryAutonomy)
    {
        parent::__construct($price, $brand);
        $this->batteryAutonomy = $batteryAutonomy;
    }

    public function getCharacteristics(): array
    {
        $characteristics = parent::getCharacteristics(); // TODO: Change the autogenerated stub
        $characteristics['batteryAutonomy'] = $this->batteryAutonomy;
        return $characteristics;
    }

}