<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0tPaicQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0tPaicQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0tPaicQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0tPaicQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0tPaicQ\App_KernelDevDebugContainer([
    'container.build_hash' => '0tPaicQ',
    'container.build_id' => '3e00ac67',
    'container.build_time' => 1613672251,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0tPaicQ');
