<?php

namespace ContainerOeAUphs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2Lvw2eaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Lvw2ea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2Lvw2ea'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exr' => ['privates', '.errored..service_locator.2Lvw2ea.App\\Entity\\Exercice', NULL, 'Cannot autowire service ".service_locator.2Lvw2ea": it references class "App\\Entity\\Exercice" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.2Lvw2ea.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.2Lvw2ea": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'exr' => 'App\\Entity\\Exercice',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
