<?php

namespace ContainerOeAUphs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerformanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.B1_W2fm.App\Entity\Performance' shared service.
     *
     * @return \App\Entity\Performance
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.B1_W2fm": it references class "App\\Entity\\Performance" but no such service exists.');
    }
}
