<?php

namespace Container0tPaicQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0AyyMAcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0AyyMAc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0AyyMAc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'exr' => ['privates', '.errored..service_locator.0AyyMAc.App\\Entity\\Exercice', NULL, 'Cannot autowire service ".service_locator.0AyyMAc": it references class "App\\Entity\\Exercice" but no such service exists.'],
        ], [
            'exr' => 'App\\Entity\\Exercice',
        ]);
    }
}
