<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1mFlC1K\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1mFlC1K/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container1mFlC1K.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container1mFlC1K\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container1mFlC1K\App_KernelProdContainer([
    'container.build_hash' => '1mFlC1K',
    'container.build_id' => '5020d872',
    'container.build_time' => 1612376610,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1mFlC1K');
